version: '3.8'

services:
  web:
    restart: always
    build: .
    command: uvicorn app.main:app --host 0.0.0.0
    volumes:
      - .:/app
    ports:
      - "8008:8000"
  postgres:
   restart: always
   image: postgres:latest
   environment:
     POSTGRES_USER: user_user
     POSTGRES_PASSWORD: password_password
     POSTGRES_DB: prijateli_tree
   volumes:
     - postgres:/var/lib/postgresql/data
   ports:
     - "5432:5432"

volumes:
  postgres:
    driver: local
