version: '3.8'

volumes:
  postgres:
    driver: local

services:
  postgres:
    restart: always
    image: postgres:latest
    environment:
      POSTGRES_USER: user_user
      POSTGRES_PASSWORD: password_password
      POSTGRES_DB: prijateli_tree
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5433:5433"
  web:
    restart: always
    build: .
    command: uvicorn --host 0.0.0.0 --port 8000 --reload prijateli_tree.app.main:app
    volumes:
      - .:/app
    links:
      - postgres:postgres
    expose:
      - "8000"
    ports:
      - "8000:8000"
