version: '3.8'

volumes:
  postgres:
    driver: local

services:
  postgres:
    restart: always
    image: postgres:latest
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: 'prijateli_tree'
    volumes:
      - ./scripts/create_database.sql:/docker-entrypoint-initdb.d/create_database.sql
      - postgres:/var/lib/postgresql@14/data:rw
    ports:
      - "51042:5432"

  web:
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
    command: uvicorn prijateli_tree.app.main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    expose:
      - "8000"
    environment:
      ENV: "${ENV-development}"
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: 'prijateli_tree'
      DATABASE_URL: "postgresql://postgres:postgres@postgres/prijateli_tree"
      LOGIN_SECRET_KEY: '3a5f3125e1af1763756297e040cd05f8f24fcab15f78805e'
    links:
      - 'postgres:postgres'
