version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: uvicorn prijateli_tree.app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    environment:
      - SQLALCHEMY_DATABASE_URI=postgresql+psycopg2://postgres:postgres@db:5432/prijateli_tree
    depends_on:
      - db

  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=prijateli_tree

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=pgadmin4@pgadmin.org
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    depends_on:
      - db
