[tool.poetry]
name = "untitled otree application"
version = "0.1.0"
description = ""
authors = ["michplunkett <5885605+michplunkett@users.noreply.github.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
otree = "^5.10.3"
alembic = "^1.11.3"
psycopg2 = "^2.9.7"

[tool.poetry.group.dev.dependencies]
pre-commit = "^3.3.3"

[tool.black]
line-length = 80
safe=true
target_version = ['py311']

[tool.isort]
src_paths = ["*.py", "./UntitledApp/*"]
profile= "black"
line_length = 80
lines_after_imports= 2
skip = [".gitignore"]

[tool.ruff]
fixable = ["ALL"]
include = ["*.py", "./UntitledApp/*"]
line-length = 80
target-version = "py311"
select = ["D"]

[tool.ruff.extend-per-file-ignores]
"__init__.py" = ["D104"]

[tool.ruff.pydocstyle]
convention = "numpy"

[tool.mypy]
python_version = "3.11"
no_implicit_optional = true

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
