[tool.poetry]
name = "untitled otree application"
version = "0.1.0"
description = ""
authors = ["michplunkett <5885605+michplunkett@users.noreply.github.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[tool.poetry.group.dev.dependencies]
pre-commit = "^3.3.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
