name: Continuous-Integration

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      ENV: "testing"
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
      - uses: actions/checkout@v3
      - name: Run tests
        run:  make test

  export-requirements-txt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: divideprojects/poetry-export-requirements-action@v1
        with:
          without-hashes: true
          outfile-name: requirements.txt

  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - uses: pre-commit/action@v3.0.0
